language: python
python:
  - "3.9"
  
# Install dependencies
install:
  - pip install -r requirements.txt

# Run tests
script:
  - python static_validate.py  
  - pytest tests/
  
notifications:
  email:
    recipients:
      - notifications@example.com
    on_failure: always
